### ISSUE TITLE
HTTP protocol vulnerable to man-in-the-middle

### ISSUE THREAD

**Issue by Javantea** [dmp1ce/mycroft-bitcoinprice-skill#1]
The API used supports HTTPS and redirects from HTTP to HTTPS when you request via HTTP, so you should use the HTTPS url instead. 
https://apiv2.bitcoinaverage.com/indices/local/ticker/btcusd

**Comment by dmp1ce** [comment]
That makes sense although I'm no longer supporting this repository. Probably best fork the project, or I can give you write permissions to this repository.

**Comment by mason88** [comment]
Thank you.  The change has been made to use HTTPS.
